### PR TITLE
Added Lark-cython to the benchmarks

### PR DESCRIPTION
**Pull request by erezsh**

### CODE REVIEW

**Comment by erezsh** [comment]
P.S. it seems like `pe` has gotten even faster? I'm amazed at how fast it is now!

**Comment by goodmami** [comment]
Lark has a cython version now? That's very exciting; I'm looking forward to running the benchmarks!

And yes, `pe` has gotten quite a bit faster since I got its Cython version working well. I have wheels built against many platforms, so I thought it was safe to make it the default when one does `pip install pe`. I also decided that it was reasonably stable so I took it out of "alpha" status. Unfortunately, my new job (which I greatly enjoy) does not leave a lot of time for these hobbies, so I'll be slow to respond to PRs and things. The changes look good to me, so if the code passes the tests feel free to merge it yourself.

**Comment by erezsh** [comment]
Yes, it's pretty cool. I had it in mind for a while, but now I had a chance to do it as part of my work for a client. It makes parsing/lexing about twice as fast, which means it's 50% to 80% faster in these benchmarks. (some time is spent in the tree construction and evaluation)

> I got its Cython version working well

Ah that makes sense! I was wondering how pure python beats my cython version :)

Still, it's very cool that you got it that fast..

**Comment by erezsh** [comment]
(The only test that fails is for pyparsing and has something to do with recursion. Anyway, it's not from these changes)

**Comment by goodmami** [comment]
RE pyparsing, could be an update in pyparsing such that it requires more calls per step than before? In any case, I agree it's not due to your changes.

BTW thanks for merging. And, sorry, I still haven't gotten an automated way to update the charts or make them prettier.

**Pull request merged**
